# Generated by Django 6.0.5 on 2026-06-02 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic', '0008_delete_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'pending'), ('PAID', 'paid'), ('EXPIRED', 'expired')], max_length=100)),
                ('type', models.CharField(choices=[('CONSULTATION', 'consultation'), ('CANCELLATION_FEE', 'cancellation fee'), ('NO_SHOW_FEE', 'no show fee')], max_length=100)),
                ('session_url', models.URLField()),
                ('session_id', models.CharField(max_length=100)),
                ('money_to_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='clinic.appointment')),
            ],
        ),
    ]
