# Generated by Django 6.0.5 on 2026-06-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('PAID', 'paid'), ('EXPIRED', 'expired')], default='PENDING', max_length=100),
        ),
    ]
