# Generated by Django 6.0.5 on 2026-06-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='session_url',
            field=models.URLField(max_length=500),
        ),
    ]
