# Generated by Django 6.0.5 on 2026-05-23 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='specialization',
            new_name='specializations',
        ),
    ]
