# Generated by Django 6.0.5 on 2026-05-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_rename_specialization_doctor_specializations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specializations',
            field=models.ManyToManyField(related_name='doctors', to='clinic.specialization'),
        ),
    ]
