# Generated by Django 6.0.5 on 2026-05-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_alter_doctor_specializations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorslot',
            name='end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='doctorslot',
            name='start',
            field=models.DateTimeField(),
        ),
    ]
