# Generated by Django 6.0.5 on 2026-05-24 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_alter_doctorslot_end_alter_doctorslot_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorslot',
            name='doctor_id',
            field=models.IntegerField(),
        ),
    ]
