# Generated by Django 6.0.5 on 2026-05-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_alter_doctorslot_doctor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor_slot_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='appointment_id',
            field=models.IntegerField(),
        ),
    ]
